source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'GraphicEditKit_Example' do
  pod 'GraphicEditKit', :path => '../'

  target 'GraphicEditKit_Tests' do
    inherit! :search_paths

    
  end
end
